### ISSUE TITLE
ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' 

### ISSUE THREAD

**Issue by 1043** [hatchetProject/AI-Driver#1]
(python3) [root@us2:/data1/AI-Driver]$ 
python DataLoader.py -pp DriverBase/training_Y_orig.xls -pn DriverBase/training_N_orig.xls -op DriverBase/Orig_Data.npy
Traceback (most recent call last):
  File "DataLoader.py", line 11, in <module>
    from sklearn.preprocessing import Imputer
ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (/root/anaconda3/envs/python3/lib/python3.8/site-packages/sklearn/preprocessing/__init__.py)

should be this.
#from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer as Imputer

**Comment by hatchetProject** [comment]
Thanks for your comment! This should be the inconsistency between Python2 and Python3.

The code is modified.
