### ISSUE TITLE
NameError: name 'argparse' is not defined

### ISSUE THREAD

**Issue by 1043** [hatchetProject/AI-Driver#2]
(python3) [root@us2:/data1/AI-Driver]$ 
python DataLoader.py -pp DriverBase/training_Y_orig.xls -pn DriverBase/training_N_orig.xls -op DriverBase/Orig_Data.npy
Traceback (most recent call last):
  File "DataLoader.py", line 76, in <module>
    parser = argparse.ArgumentParser()
NameError: name 'argparse' is not defined

How to fix this?

**Comment by hatchetProject** [comment]
Just do:
pip install argparse
in command line
