### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by christianbosselmann** [hatchetProject/AI-Driver#7]
Hi,

The link for the pre-computed AI-Driver scores for all genome-wide possible missense variants (http://aidriver.maolab.org) appears to be dead. Are these scores available anywhere else?

Thanks

Christian

**Comment by hatchetProject** [comment]
Hi Christian, 

I suppose you meant the "Download link" under "Other links". Strangely the link is valid for me. You can try to access the link via url, which is: 
http://aidriver.tania.wang:580/download/Varcards.main.missense.GenomAD.ht0.1.AI-Driver-score.hg19.txt.gz

If it still doesn't work, try to change your browser. Safari and Chrome both works for me. 

Best, 
Haoxuan

**Comment by christianbosselmann** [comment]
Error on my end. Apologies. Thanks for a great resource.
